### ISSUE TITLE
Button for Compare & Pull Request Not Visible

### ISSUE THREAD

**Issue by rdelcampo** [wbuchanan/sdpConvening2017#13]
After saving the changes I didn't see the green button that was referenced in the pre-work screen shot.  I've attached a screenshot showing how it looked after I committed the change to the `prework` branch below.

<img width="1280" alt="screen shot 2017-04-29 at 12 33 30 pm" src="https://cloud.githubusercontent.com/assets/15572074/25557124/c667396e-2cd8-11e7-8c0e-b1e3b903109d.png">

**Comment by wbuchanan** [comment]
@jsonbecker

This might be the result of different integrations I had set up on my account a while ago.  Do you end up seeing something different/similar?  

In either case I'll take this screen shot, annotate it, and toss it into `prework.md` over the weekend.

**Comment by wbuchanan** [comment]
@jsonbecker, @nathant23, @daphnejenkins,

I annotated the screen shot that @rdelcampo submitted in this issue and added it to the prework file.  This should help to avoid confusion for anyone else that wouldn't see the Compare & Create Pull Request button.
