### ISSUE TITLE
Session presentation outline

### ISSUE THREAD

**Issue by nathant23** [wbuchanan/sdpConvening2017#19]
I created a markdown document of a draft outline that I have in my forked instance of the repository in a branch called presentationOutline.  

I wasn't quite sure how we wanted to do this.  Do we want this on an existing branch?

**Comment by wbuchanan** [comment]
@nathant23 
Just created this branch here.  You should be able to pull the changes (pretty minor to the README file) and then you'll be able to submit a PR.


@jsonbecker & @daphnejenkins,
We can put our individual outlines in the presentationOutline branch and once we have our outlines done we can merge the branch into the master branch.
