### ISSUE TITLE
Committing to Master Branch

### ISSUE THREAD

**Issue by wbuchanan** [wbuchanan/sdpConvening2017#5]
@nathant23, @daphnejenkins, & @jsonbecker,

How do we want to handle pushing things into master?  Should we go with a more typical/traditional approach (e.g., create feature branches, set up some general process for code review, and then merge the PR) or something else?

**Comment by wbuchanan** [comment]
@jsonbecker,

Would this be a topic that you were thinking about addressing a bit more in your part of the session?  If so I'm fine with going with whatever merge strategy you want to use for things and if not I can try working this into my part of things if it isn't going to be covered by anyone else.

**Comment by jsonbecker** [comment]
I think ideally we should go feature branch with a PR to master with one review required to get merged in.

--
Jason Becker

**Comment by wbuchanan** [comment]
@jsonbecker

That works for me.  I submitted a PR for the session proposal and tagged @nathant23 to review.  I imagine we'll get several different PRs targeting the prework branch as people start completing and figured it might create some merge conflicts that we could use to talk about managing collaborative workflows and/or product management type issues.
