### ISSUE TITLE
Demonstration project for presentation?

### ISSUE THREAD

**Issue by jknowles** [wbuchanan/sdpConvening2017#6]
Any chance you might be interested in tying in to the nascent OpenSDP project to demonstrate Git/GitHub based collaboration?

We are looking to make available some repositories -- one that contains a synthetic data engine, and one that contains an analysis built on that synthetic data -- and want to get input, corrections, improvements, etc. from the community using GitHub. 

Showing people how to use Git/GitHub while also demonstrating the OpenSDP repository as an open and public place to contribute might be a good motivating example?

Feel free to disregard if you have something else in mind and this takes you far afield from that.

**Comment by wbuchanan** [comment]
@jknowles 
I think this would be an awesome idea.  I imagine @nathant23, @daphnejenkins, and @jsonbecker would all agree that this would also be a good way to get the word out about things and provide a good model that could start chipping away at some of the hesitation that some organizations may have about open sourcing their development efforts and/or collaborating across organizations.

**Comment by jknowles** [comment]
Let me know what a good next step is. I think I'll have some repositories able to see the light of day shortly that you can build into your materials -- and I'll run this by the team I'm working with at SDP on OpenSDP as well. 

Thanks!

**Comment by wbuchanan** [comment]
@jknowles 
Depending on the contents of the repository it might align really well with some of the stuff that @nathant23 was thinking about for the talk at convening.

**Comment by wbuchanan** [comment]
@jknowles 
We have a call set up with Rebecca and the rest of our group this Thursday so we can run this by her as well if you think that would be useful/helpful.  Also, if you had any training materials that you've put together for teaching people how to use a VCS feel free to let us know and we can list it as a resource in the Wiki for the repository.

**Comment by nathant23** [comment]
@jknowles @wbuchanan 
I think this sounds great.  Excited to talk about this tomorrow.

**Comment by jknowles** [comment]
Yes, run it by her. I'll run it by my team too. I will put resources together and get back to you early next week!

**Comment by wbuchanan** [comment]
@jknowles 
Just let us know when the thing is ready and we can work on getting it tied in.  I think it'd be pretty easy to throw a reference or two into a similar strategy into the talk I'm going to be doing with Bart and Cara (e.g., creating a research agenda and mentioning dissemination of methods/results as part of it).

**Comment by jknowles** [comment]
Here is the R version of the thing @wbuchanan 

https://github.com/strategicdataproject/contribute-R

**Comment by wbuchanan** [comment]
Will there be similar template repositories for other languages as well?  Thinking more about Stata/Python, but possibly Julia down the road.

**Comment by jknowles** [comment]
Stata for sure. Others will be up to the community to create.

**Comment by wbuchanan** [comment]
@nathant23,
Do you have a similar repository together for the examples that you were wanting to work through?  @jsonbecker and I connected yesterday and figured it might be useful if we were able to build on the same initial process from start to finish.

**Comment by jknowles** [comment]
As an FYI -- I think Stata won't be finished up until Monday or Tuesday next week...

**Comment by wbuchanan** [comment]
@jknowles
Is the purpose of the Stata based repository for people to be able to install the work from within Stata?  If so, I can add throw together a bit of info about the `gh-pages` branch and the files that would need to be present in order to use the `net install` command in a way that would be analogous to `devtools::install_github`.

**Comment by jknowles** [comment]
No - don't take a crack at anything. Our team has some good ideas on what the Stata piece needs to look like and will pull it together shortly. 

The idea is to have an empty template repository that has some guidelines on how to use `webdoc` to make an equivalent of R Markdown, and to structure an analysis into subfolders following the OpenSDP recommendations for organizing analysis projects.
